// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://j6ngyh5f45albosbh3sdjj4szm.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cognito_identity_pool_id": "us-east-1:452e5811-58e7-4cce-8b39-90db30a8eba3",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_buFSrhliB",
    "aws_user_pools_web_client_id": "1qkrcfqgqv63hk594qi92q5hqi",
    "oauth": {},
    "aws_user_files_s3_bucket": "kennyslist0a68ad13e69142fb89779b2dba58e9dd145823-kennyslist",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
