// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_appsync_graphqlEndpoint": process.env.GRAPHQL,
    "aws_appsync_region": process.env.REGION,
   	"aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
};


export default awsmobile;
